name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"


jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"
